server:
  port: 8888

spring:
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    searchLocations: file:///E:/new_intellij_work_plc/configurations
    application:
      name: spring-config
                    
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    registry-fetch-interval-seconds: 5
    fetch-registry: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 5
